MTUOC: /MTUOC

corpusSPE: sherlock-holmes-eng.txt
corpusGEN: CCMatrix-eng-spa-scores.txt.gz
corpusSELECTED: CCMatrix-Sherlock-Holmes-10M-eng-spa.txt
corpus_GEN_SEL_LINES: 10000000
corpus_GEN_MAX_READ: -1
from_scores_database: False
scores_database_name: CCMatrix-Sherlock-Holmes-eng-spa.sqlite
valsize: 5000
evalsize: 5000
SLcode3: eng
SLcode2: en
TLcode3: spa
TLcode2: es

tokenize_for_language_model_creation: True
SL_TOKENIZER: MTUOC_tokenizer_eng
TL_TOKENIZER: MTUOC_tokenizer_spa

VERBOSE: True
LOG_FILE: combination_log.txt
